---
name: Class-Sniff
version: 0.08_03
author:
  - 'Curtis "Ovid" Poe <ovid@cpan.org>'
abstract: Look for class composition code smells
license: perl
resources:
  license: ~
requires:
  B::Concise: 0.66
  Devel::Symdump: 2.08
  Digest::MD5: 2.36
  File::Find::Rule: 0.3
  Graph::Easy: 0.64
  List::MoreUtils: 0.22
  Sub::Identify: 0.03
  Text::SimpleTable: 0.05
build_requires:
  Test::Most: 0.2
provides:
  Class::Sniff:
    file: lib/Class/Sniff.pm
    version: 0.08_03
  Class::Sniff::App:
    file: lib/Class/Sniff/App.pm
    version: 0.08_03
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
