---
name: Class-Sniff
version: 0.07
author:
  - 'Curtis "Ovid" Poe <ovid@cpan.org>'
abstract: Look for class composition code smells
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  B::Concise: 0.66
  Devel::Symdump: 2.08
  Digest::MD5: 2.36
  Graph::Easy: 0.64
  List::MoreUtils: 0.22
  Sub::Information: 0.1
  Text::SimpleTable: 0.05
  Tree: 1.01
build_requires:
  Test::Most: 0.2
provides:
  Class::Sniff:
    file: lib/Class/Sniff.pm
    version: 0.07
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
